### ISSUE TITLE
Unreachable switch-labels in CharSeq class

### ISSUE THREAD

**Issue by wrandelshofer** [lukehutch/pikaparser#2]
Hi Luke,
Some of the switch-labels in method toString in CharSeq class are unreachable. 

The surrounding if-statement checks if c is in the range [32,126] and then executes the then-clause. 
Therefore in the else-clause, the switch-statement will never reach the clauses for '\'', '\"', and '\\' because these characters are in the range [32,126].

```java
                if (c >= 32 && c <= 126) {
                    buf.append(c);
                } else {
                    switch (c) {
                    case '\t':
                        buf.append("\\t");
                        break;
                    case '\n':
                        buf.append("\\n");
                        break;
                    case '\r':
                        buf.append("\\r");
                        break;
                    case '\b':
                        buf.append("\\b");
                        break;
                    case '\f':
                        buf.append("\\f");
                        break;
                    case '\'':
                        buf.append("\\'");
                        break;
                    case '\"':
                        buf.append("\\\"");
                        break;
                    case '\\':
                        buf.append("\\\\");
                        break;
                    default:
                        buf.append("\\u" + String.format("%04x", (int) c));
                    }
                }
```

**Comment by lukehutch** [comment]
Good catch -- thanks!

**Comment by wrandelshofer** [comment]
Wow, you are fast! Thank you for the fix!

**Comment by lukehutch** [comment]
@wrandelshofer Thanks for giving the code a test run! I'm happy you're finding all these issues. Are you trying out the code because you're curious about the parsing algorithm, or because you want to use this in a real-world application?

**Comment by wrandelshofer** [comment]
I am looking for a design that separates grammar definition, parsing and abstract syntax tree building without involving a code generation step. I am very much intrigued by the approach that you took with MetaGrammar and ClauseFactory in Pika Parser for the grammar definition.
 
The bottom up algorithm of the Pika Parser is also very interesting, however it is not clear to me, how good error reporting can be implemented.

**Comment by lukehutch** [comment]
Oh, the form in MetaGrammar is really just a way to build clause trees using Java syntax -- you have to bootstrap a parser generator somehow!

Error reporting is actually really straightforward -- call `grammar.getSyntaxErrors(memoTable, input, "Statement", "Program")` or similar (just list all the grammar rules that should span all of the input in the last varargs parameter). Any character range that is not spanned by a match of one of the named rules is returned in the result. You can print out the characters in those ranges as syntax errors. (I'll go document that...)
