### ISSUE TITLE
Introduce parallel data processing

### ISSUE THREAD

**Issue by elfring** [lukehutch/pikaparser#27]
I guess that this parser contains software components and processing phases which could benefit from parallelisation.
:thinking: How do you think about to [use the technique “multi-threading”](https://docs.oracle.com/javase/tutorial/essential/concurrency/index.html "Developing concurrent software")?

**Comment by lukehutch** [comment]
Hi, the paper talks about this. An early version of the parser was fully parallelized -- and it would have probably been the first fine-grain-parallelized parsing algorithm ever, since almost no parsing algorithm has obvious opportunities for parallelization. However, the DP data dependencies don't actually allow for parallelization, as the DP table entries have to be filled in with a strict total ordering (as opposed to a partial ordering). Some amount of speculative evaluation could be used, but it would make the parser more complicated, with questionable additional value.

**Comment by elfring** [comment]
I propose to consider that parallel data processing can help also on an other granularity.
:thinking: How do you think about [a corresponding pipeline](https://en.wikipedia.org/wiki/Pipeline_(software) "Description for usage of software pipelines")?
1. Input
2. Internal data processing
3. Output

**Comment by lukehutch** [comment]
Input and output probably take 0.001% of the total time here, given a relatively large grammar -- even though I/O is orders of magnitude slower than processing. And also, files used by parsers tend to be small.

One of my specializations is parallel computing, so trust me, I am not missing a fundamental opportunity here.

However feel free to try it yourself, and if you show some compelling benchmarks, I'll be happy to say I'm wrong.

**Comment by elfring** [comment]
I got into the mood to clarify if it could become interesting to move processing for input and output data to dedicated threads (when parallelisation looks questionable at other places).

**Comment by lukehutch** [comment]
That's known as "pipelining", and it works if you have multiple subsequent stages of processing that are bound to the same resource (eg. there are two successive compute-intensive stages, where one stage only feeds information to the next stage, but not the other way). But it does not speed things up (or may even slow things down) if two successive stages are bound to different resources (here, I/O and processing).

**Comment by elfring** [comment]
I imagine that internal data structures can be constructed in parallel while data are extracted from input files.

**Comment by lukehutch** [comment]
You need to take a close look at the algorithm and point out exactly where you're suggesting parallelization can be introduced. Unfortunately a hunch doesn't help.

**Comment by elfring** [comment]
Can any threads take care of grammar descriptions and related program configuration files?

**Comment by elfring** [comment]
:crystal_ball: Would the situation look different if a parsing service will be taken into account?

**Comment by lukehutch** [comment]
There are no configuration files. Only grammar files and input string.

Sure, you could create a parsing service in a different thread if you want to. But that's part of your program, not the parser itself. And it won't make things faster. If you want to do this though, see:

https://langserver.org/
