### ISSUE TITLE
Publish source file for the research paper

### ISSUE THREAD

**Issue by elfring** [lukehutch/pikaparser#29]
Some source files are provided according to [the paper “Pika parsing: reformulating packrat parsing as a dynamic programming algorithm solves the left recursion and error recovery problems”](https://arxiv.org/abs/2005.06444 "Descriptions from May 2020").
How do you think about to publish the source file also for this document?

**Comment by lukehutch** [comment]
Almost all papers on arXiv have LaTeX source available.

https://arxiv.org/format/2005.06444

**Comment by elfring** [comment]
Can TeX source files be managed also in this repository?
(Do you prefer to store them separately?)

**Comment by lukehutch** [comment]
If you were masochistic enough to write your document in pure TeX, sure. But there is no reason to upload generated files, only original source.

**Comment by elfring** [comment]
I find GitHub functionality (for example) also helpful for original TeX source files.
